grant alter any COLLATION TO PUBLIC;
grant alter any DOMAIN TO PUBLIC;
grant alter any EXCEPTION TO PUBLIC;
grant alter any FILTER TO PUBLIC;
grant alter any FUNCTION TO PUBLIC;
grant alter any SEQUENCE TO PUBLIC;
grant alter any PACKAGE TO PUBLIC;
grant alter any PROCEDURE TO PUBLIC;
grant alter any ROLE TO PUBLIC;
grant alter any TABLE TO PUBLIC;
grant alter any VIEW TO PUBLIC;
grant alter any CHARACTER SET TO PUBLIC;
