using FirebirdDbComparer.Compare;

namespace FirebirdDbComparer.Tests.Compare.ComparerTestsData.Changing;

public class IdentityFromAlwaysToDefaultAndIncrement : ComparerTests.TestCaseStructure
{
    public override bool IsCompatibleWithVersion(TargetVersion targetVersion)
    {
        return targetVersion.AtLeast(TargetVersion.Version40);
    }

    public override string Source => @"
create table t(i int generated by default as identity (increment by 10))				
";

    public override string Target => @"
create table t(i int generated always as identity)	
";
}
